import type { BestCreatorCursorListTypes } from "@/types/best/bestTypes"

export const BestCreatorDatas: BestCreatorCursorListTypes = {
	data: [
		{
			id: 1,
			name: "Creator A",
			rank: 1,
			rankChange: 2,
			image: "https://example.com/imageA.jpg",
		},
		{
			id: 2,
			name: "Creator B",
			rank: 2,
			rankChange: -1,
			image: "https://example.com/imageB.jpg",
		},
		{
			id: 3,
			name: "Creator C",
			rank: 3,
			rankChange: 0,
			image: "https://example.com/imageC.jpg",
		},
		{
			id: 4,
			name: "Creator D",
			rank: 4,
			rankChange: 1,
			image: "https://example.com/imageD.jpg",
		},
		{
			id: 5,
			name: "Creator E",
			rank: 5,
			rankChange: -2,
			image: "https://example.com/imageE.jpg",
		},
		{
			id: 6,
			name: "Creator F",
			rank: 6,
			rankChange: 0,
			image: "https://example.com/imageF.jpg",
		},
		{
			id: 7,
			name: "Creator G",
			rank: 7,
			rankChange: 3,
			image: "https://example.com/imageG.jpg",
		},
		{
			id: 8,
			name: "Creator H",
			rank: 8,
			rankChange: -1,
			image: "https://example.com/imageH.jpg",
		},
		{
			id: 9,
			name: "Creator I",
			rank: 9,
			rankChange: 2,
			image: "https://example.com/imageI.jpg",
		},
		{
			id: 10,
			name: "Creator J",
			rank: 10,
			rankChange: -3,
			image: "https://example.com/imageJ.jpg",
		},
		{
			id: 11,
			name: "Creator K",
			rank: 11,
			rankChange: 0,
			image: "https://example.com/imageK.jpg",
		},
		{
			id: 12,
			name: "Creator L",
			rank: 12,
			rankChange: 1,
			image: "https://example.com/imageL.jpg",
		},
		{
			id: 13,
			name: "Creator M",
			rank: 13,
			rankChange: -1,
			image: "https://example.com/imageM.jpg",
		},
		{
			id: 14,
			name: "Creator N",
			rank: 14,
			rankChange: 2,
			image: "https://example.com/imageN.jpg",
		},
		{
			id: 15,
			name: "Creator O",
			rank: 15,
			rankChange: -2,
			image: "https://example.com/imageO.jpg",
		},
		{
			id: 16,
			name: "Creator P",
			rank: 16,
			rankChange: 0,
			image: "https://example.com/imageP.jpg",
		},
		{
			id: 17,
			name: "Creator Q",
			rank: 17,
			rankChange: 3,
			image: "https://example.com/imageQ.jpg",
		},
		{
			id: 18,
			name: "Creator R",
			rank: 18,
			rankChange: -1,
			image: "https://example.com/imageR.jpg",
		},
		{
			id: 20,
			name: "Creator T",
			rank: 20,
			rankChange: -3,
			image: "https://example.com/imageT.jpg",
		},
	],
	nextCursor: "nextCursor123",
	hasNextPage: true,
}
