module.exports = {
  trailingComma: "all",
  quoteProps: "as-needed",
  tabWidth: 2,
  useTabs: true,
  semi: false,
  singleQuote: false,
  printWidth: 80,
  proseWrap: "preserve",
  endOfLine: "crlf",
  jsxSingleQuote: false,
  bracketSameLine: true,
  bracketSpacing: true,
  arrowParens: "always",
  plugins: ["prettier-plugin-tailwindcss"],
}
